spring.datasource.url=jdbc:mariadb://localhost:3308/westeros_db
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.username=user
spring.datasource.password=123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true

themoviedb.api.key=242003333bfca71d4c634ca0a2bbd2be
themoviedb.api.host=api.themoviedb.org
themoviedb.api.version=3

server.port=8081
